version: "2"
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - dist
    - profile

output:
  sort-results: true

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: exported
        disabled: false
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  misspell:
    locale: US
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/snrsw/gh-own

linters:
  enable:
    - errorlint
    - godot
    - gosec
    - misspell
    - revive
    - funcorder
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gocyclo
    - cyclop

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tmpmod
      - third_party$
      - builtin$
      - examples$
